export const OnchainLevelingABI = [
  {
    inputs: [
      { internalType: "address", name: "initialOwner", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyRegistered", type: "error" },
  { inputs: [], name: "InvalidCharacter", type: "error" },
  { inputs: [], name: "NotRegistered", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ProgressZero", type: "error" },
  { inputs: [], name: "TaskAlreadyCompleted", type: "error" },
  { inputs: [], name: "TaskDisabled", type: "error" },
  { inputs: [], name: "TaskNotFound", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "uint8",
        name: "characterType",
        type: "uint8",
      },
    ],
    name: "Registered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint32", name: "day", type: "uint32" },
      {
        indexed: true,
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "progress",
        type: "uint16",
      },
      { indexed: false, internalType: "uint16", name: "goal", type: "uint16" },
      {
        indexed: false,
        internalType: "uint256",
        name: "xpAwarded",
        type: "uint256",
      },
    ],
    name: "TaskCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
    ],
    name: "TaskDefCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
    ],
    name: "TaskDefUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint32", name: "day", type: "uint32" },
      {
        indexed: true,
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "oldProgress",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "newProgress",
        type: "uint16",
      },
    ],
    name: "TaskProgressed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalXp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newLevel",
        type: "uint32",
      },
    ],
    name: "XPAwarded",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "taskId", type: "uint256" },
      { internalType: "uint16", name: "amount", type: "uint16" },
    ],
    name: "addProgress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint8", name: "ttype", type: "uint8" },
      { internalType: "uint16", name: "goal", type: "uint16" },
      { internalType: "uint16", name: "xp", type: "uint16" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "createTaskDef",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getProfile",
    outputs: [
      { internalType: "string", name: "", type: "string" },
      { internalType: "uint8", name: "", type: "uint8" },
      { internalType: "uint32", name: "", type: "uint32" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bool", name: "", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint32", name: "day", type: "uint32" },
      { internalType: "uint256", name: "taskId", type: "uint256" },
    ],
    name: "getProgress",
    outputs: [
      { internalType: "uint16", name: "progress", type: "uint16" },
      { internalType: "bool", name: "completed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "taskId", type: "uint256" }],
    name: "getTaskDef",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint8", name: "ttype", type: "uint8" },
      { internalType: "uint16", name: "goal", type: "uint16" },
      { internalType: "uint16", name: "xp", type: "uint16" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "levelOf",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "offset", type: "uint256" },
      { internalType: "uint256", name: "limit", type: "uint256" },
    ],
    name: "listTaskDefs",
    outputs: [
      { internalType: "uint256[]", name: "ids", type: "uint256[]" },
      { internalType: "string[]", name: "names", type: "string[]" },
      { internalType: "uint8[]", name: "ttypes", type: "uint8[]" },
      { internalType: "uint16[]", name: "goals", type: "uint16[]" },
      { internalType: "uint16[]", name: "xps", type: "uint16[]" },
      { internalType: "bool[]", name: "enableds", type: "bool[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "nextLevelXp",
    outputs: [
      { internalType: "uint256", name: "remaining", type: "uint256" },
      { internalType: "uint256", name: "nextLevelCumulative", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint8", name: "characterType", type: "uint8" },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "taskDefCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "todayAllProgress",
    outputs: [
      { internalType: "uint32", name: "day", type: "uint32" },
      { internalType: "uint16[]", name: "progresses", type: "uint16[]" },
      { internalType: "bool[]", name: "completeds", type: "bool[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "taskId", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint8", name: "ttype", type: "uint8" },
      { internalType: "uint16", name: "goal", type: "uint16" },
      { internalType: "uint16", name: "xp", type: "uint16" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "updateTaskDef",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "xpOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];
